name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update && sudo apt-get install -y clang-format
          find src include ouro_mod tests -iname '*.cc' | xargs clang-format --dry-run --Werror
          if command -v zig >/dev/null; then
            zig fmt --check build.zig
          fi

  static-analysis:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
          sudo apt-get update && sudo apt-get install -y clang-tidy
          find src include -iname '*.cc' | xargs clang-tidy -quiet

  zig-mod-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: goto-bus-stop/setup-zig@v2
        with:
          version: 0.14.1
      - run: zig build mod-test
